-- ============================================================
-- Enums
-- Use DO blocks so this script is safe to run multiple times.
-- ============================================================

DO $$ BEGIN
    CREATE TYPE layer_enum AS ENUM ('raw', 'processed', 'curated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE run_status AS ENUM ('running', 'completed', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE batch_status AS ENUM ('running', 'completed', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================
-- pipeline_runs
-- Tracks every execution of the ingestion pipeline.
-- id: auto-increment integer
-- ============================================================

CREATE TABLE IF NOT EXISTS pipeline_runs (
    id           SERIAL      PRIMARY KEY,
    status       run_status  NOT NULL DEFAULT 'running',
    started_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ                            -- NULL until the run finishes
);

-- ============================================================
-- datasets
-- Registry of logical datasets (one row per named dataset).
-- id: UUID generated by PostgreSQL
-- ============================================================

CREATE TABLE IF NOT EXISTS datasets (
    id     UUID       PRIMARY KEY DEFAULT gen_random_uuid(),
    name   TEXT       NOT NULL UNIQUE,
    layer  layer_enum NOT NULL,
    bucket TEXT       NOT NULL,
    source TEXT       NOT NULL
);

-- ============================================================
-- data_batches
-- One row per file/object written to the data lake.
-- id: auto-increment integer
-- ============================================================

CREATE TABLE IF NOT EXISTS data_batches (
    id              SERIAL       PRIMARY KEY,
    dataset_id      UUID         NOT NULL REFERENCES datasets(id),
    pipeline_run_id INTEGER      NOT NULL REFERENCES pipeline_runs(id),
    path            TEXT         NOT NULL,   -- MinIO object key
    record_count    INTEGER,                 -- NULL when unknown or failed
    status          batch_status NOT NULL DEFAULT 'running',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ============================================================
-- schemas
-- Field-level schema definitions per dataset.
-- PK: composite (dataset_id, field_name)
-- ============================================================

CREATE TABLE IF NOT EXISTS schemas (
    dataset_id  UUID NOT NULL REFERENCES datasets(id),
    field_name  TEXT NOT NULL,
    field_type  TEXT NOT NULL,
    PRIMARY KEY (dataset_id, field_name)
);
